apiVersion: v2
name: service-helper
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: default-app
    version: ${DEFAULT_APP_CHART_VERSION}
    repository: ${CHART_REPO_BASE_URL}
    export-values:
      - parent: werf
        child: werf
